sudo: required

language: python

python:
  - 3.6

services:
  - docker

env:
  global:
    - CODECOV_TOKEN=eb7d0b33-d7f0-4c68-9e20-71efff8ca75e
    - DOCKER_USERNAME=alaxalves
    - secure: ByMFGg70bJ23aoJlt/NFqeGoddkXGK66kwqtuIK+FJGSglqPM4QbgrUr8d1Cz+bltQhnLeHZ4/ahmCjh93rfeowqcoiwyRXgkJ/tj3aARGAZLL99vZqxnelx3g2DEtJ/VinqYw/MNZ7WRZTa5EaLR6D+fsIKQJQO46w4G9I3Ivzck/hTKoFbE6hv5Jua2gtvtlM/MEMblS+gQU7m8wrXWM1zqjTBP7MR82lm+JTqXFoYAHIvOYPDQzv11VH0lR1NRbYi2//V7lig2Ro4vHs4JWCHHOlyiM4cq/RCbmxwKdY7uJej927xSmseUt5BLCkGFnWzDqkMxIPDoP5QPWU/eMmIFCbSA32H5XgW4zF+gjI7mR6pH0/wzfwVuhCtN/YksuXsbvNJa90EEFsXBS5fdQtDQmRr7WF/YtwudJG1eryiyzNbsC07//NRS9WChrXWqPzvCTwjyeNcY1fvEvUZWWUNajWX25U17iYPHp7sKbcn/vL1IeI1r9d95EZK1HlCAigEO186nm2Wx8QXVhaviE27LjxlYpD6/Y8+qBGoSCEj9YRP5B3gX8v2HldZsoTilgah/aeRCmAIb+ZQ2cbKRLYPiBwbgvsBWsy9An6vYVYFCuQObbEf/tm5sGARpnpAVeQ/q2H/bwV7wsR7nJGVv1uVx7WagmEFZMhRWqibH0o= #DOCKER_PASSWORD
  matrix:
    - TASK="pytest --cov=./simian"
    - TASK="pep8 --max-line-length=90 --show-source --show-pep8 *.py */*.py */**/*.py"

install:
  - sudo apt-get install alsa-base alsa-utils pulseaudio
  - pip3 install -r requirements.txt

before_script:
  - python3 setup.py build
  - python3 setup.py install
  - python3 setup.py develop

script:
  - $TASK

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - pip install -Iv pip==8.1.1

deploy:
  - provider: pypi
    user: alaxalves
    password:
      secure: A9BgjsRjxtIq1DrmHuhyk5euxsSUJlrvK4J9idC0aBZyaxpLE3uEM+TvlLKeDD/mJoV1aPQf2fqsJmRKvaWaXq08t2SFQuiopGVkVHnmCSNHmuhm/mIVKIRPQ/zhjFVUzvx7NYb6t0FwkUFgg+U12ZU31qug8l5Y+xqcA0vH6uQB+jxhCLkwFMSJZghiMi0bFpvoY+inLhytsmAnwHpvFvaFK6zUwd66QM87t4WoOC+T/jYzoXnuH0RaveFcO8Nlw/d4n0ajMQWz8uS41saA+UNQkticpbCmXC5DE5qmPljB9mjco9B7pzs0p7Ti0mmhJKvcqArk1ZA9PCv5d7vuWAfpodayWyCuD5XiRBSziMFJYle6+VR9DcxjdTlvZ5TMUTBAKpmfw6h2ILW6RxvX/Cqwvs+AbeDr/f2yJsedGj2mTANbZ8Ta7Viagbnes97U6ek+rpgoam51kb3/XnRFVi29ByZ0HiSCuD8AbchCQTHUBFyNaI2AZPlSz4MKwoRqbtZ3kBflr42h4ftWVlR+5yCE8YYuf+T9ivDS2AwWZ8eS23auuku6MSpDEAGZD1HYySUaZDUVpi687cJwyZAYa/npq58Y9aILkdyjju5iBtHkUrSBhHZgLe8ExefbSUxokvMcTxHv+4JnaBm5GbaDQh87Na0tGKxA4zShn0cdy6E=
    on:
      branch: master
      python: 3.5
    edge:
      branch: v1.8.45

  - provider: script
    user: alaxalves
    password:
      secure: ByMFGg70bJ23aoJlt/NFqeGoddkXGK66kwqtuIK+FJGSglqPM4QbgrUr8d1Cz+bltQhnLeHZ4/ahmCjh93rfeowqcoiwyRXgkJ/tj3aARGAZLL99vZqxnelx3g2DEtJ/VinqYw/MNZ7WRZTa5EaLR6D+fsIKQJQO46w4G9I3Ivzck/hTKoFbE6hv5Jua2gtvtlM/MEMblS+gQU7m8wrXWM1zqjTBP7MR82lm+JTqXFoYAHIvOYPDQzv11VH0lR1NRbYi2//V7lig2Ro4vHs4JWCHHOlyiM4cq/RCbmxwKdY7uJej927xSmseUt5BLCkGFnWzDqkMxIPDoP5QPWU/eMmIFCbSA32H5XgW4zF+gjI7mR6pH0/wzfwVuhCtN/YksuXsbvNJa90EEFsXBS5fdQtDQmRr7WF/YtwudJG1eryiyzNbsC07//NRS9WChrXWqPzvCTwjyeNcY1fvEvUZWWUNajWX25U17iYPHp7sKbcn/vL1IeI1r9d95EZK1HlCAigEO186nm2Wx8QXVhaviE27LjxlYpD6/Y8+qBGoSCEj9YRP5B3gX8v2HldZsoTilgah/aeRCmAIb+ZQ2cbKRLYPiBwbgvsBWsy9An6vYVYFCuQObbEf/tm5sGARpnpAVeQ/q2H/bwV7wsR7nJGVv1uVx7WagmEFZMhRWqibH0o=
    script: bash scripts/sh/docker-deploy.sh
    on:
      branch: master
