language: python

python:
  - 3.5

env:
  global:
  - CODECOV_TOKEN=eb7d0b33-d7f0-4c68-9e20-71efff8ca75e

install:
  - pip3 install -r requirements.txt
  - pip3 install codecov

before_script:
  - python3 setup.py build
  - coverage run tests/

script:
  - python3 -m pytest

  after_success:
  - codecov
