version: '3.5'
services:

  app:
    container_name: simian
    image: alaxalves/simian:0.0.1
    stdin_open: true
    tty: true
    command: /bin/bash
    networks: 
      - simian
    volumes:
      - .:/home/simian

networks: 
  simian:
    name: simian-network
    